php:
    build: .
    ports:
        - "7070:80"
        - "7071:443"
    volumes:
        - ./src:/var/www/html
        - ./src/logs:/var/log/apache2
    links:
        - db

db:
    image: mysql:5.7
    ports:
        - "7072:3306"
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=applara
        - MYSQL_USER=root
        - MYSQL_DATABASE=applara